name: Auto Update Suwayomi

on:
workflow_dispatch:
schedule:
- cron: '0 0 * * *'

permissions:
contents: write

jobs:
update:
runs-on: windows-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Install Scoop
    shell: pwsh
    run: |
      Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      Invoke-RestMethod get.scoop.sh | Invoke-Expression
      scoop install git
      scoop install checkver

  - name: Update manifest
    shell: pwsh
    run: |
      checkver -u suwayomi-server-preview

  - name: Commit and push changes
    shell: pwsh
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      if ((git status --porcelain).Length -gt 0) {
        $manifest = Get-Content "bucket/suwayomi-server-preview.json" | ConvertFrom-Json
        $version = $manifest.version

        git add .
        git commit -m "suwayomi-server-preview: Update to version $version"
        git push
      }
      else {
        Write-Host "No updates available"
      }
