name: Excavator

on:
  workflow_dispatch:
  schedule:
  # Runs 4 times daily at 02:00 AM, 08:00 AM, 02:00 PM, 08:00 PM IST
  - cron: '30 20,2,8,14 * * *'
permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
